apiVersion: apps/v1
kind: Deployment
metadata:
  name: exo-devops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: exo-devops-app
  template:
    metadata:
      labels:
        app: exo-devops-app
    spec:
      containers:
        - name: exo-devops-app
          image: lorisplante/exo-devops-app:latest
          ports:
            - containerPort: 3000
