apiVersion: v1
kind: Service
metadata:
  name: exo-devops-app-service
spec:
  selector:
    app: exo-devops-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
